In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv('./heart_2020.csv')
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), object(14)
memory usage: 43.9+ MB

In [20]:
df.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [21]:
df.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  319795.000000    319795.00000  319795.000000  319795.000000
mean       28.325399         3.37171       3.898366       7.097075
std         6.356100         7.95085       7.955235       1.436007
min        12.020000         0.00000       0.000000       1.000000
25%        24.030000         0.00000       0.000000       6.000000
50%        27.340000         0.00000       0.000000       7.000000
75%        31.420000         2.00000       3.000000       8.000000
max        94.850000        30.00000      30.000000      24.000000

In [22]:
from sklearn.preprocessing import OneHotEncoder

#HeartDisease - 심장병
#Smoking - 흡연
#AlcoholDrinking - 음주
#Stroke - 뇌졸증
#DiffWalking - 디프워킹
#Diabetic - 당뇨병
#Asthma - 천식
#KidneyDisease - 신장병
#SkinCancer - 피부암

df1 = pd.get_dummies(df, columns = ['HeartDisease', 'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex', 'Diabetic', 'Asthma',
                                 'KidneyDisease', 'SkinCancer'])
df1.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,HeartDisease_No,HeartDisease_Yes,...,Diabetic_No,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy),Asthma_No,Asthma_Yes,KidneyDisease_No,KidneyDisease_Yes,SkinCancer_No,SkinCancer_Yes
0,16.60,3.0,30.0,55-59,White,Yes,Very good,5.0,1,0,...,0,0,1,0,0,1,1,0,0,1
1,20.34,0.0,0.0,80 or older,White,Yes,Very good,7.0,1,0,...,1,0,0,0,1,0,1,0,1,0
2,26.58,20.0,30.0,65-69,White,Yes,Fair,8.0,1,0,...,0,0,1,0,0,1,1,0,1,0
3,24.21,0.0,0.0,75-79,White,No,Good,6.0,1,0,...,1,0,0,0,1,0,1,0,0,1
4,23.71,28.0,0.0,40-44,White,Yes,Very good,8.0,1,0,...,1,0,0,0,1,0,1,0,1,0

In [23]:
df1['AgeCategory'].value_counts()

65-69          34151
60-64          33686
70-74          31065
55-59          29757
50-54          25382
80 or older    24153
45-49          21791
75-79          21482
18-24          21064
40-44          21006
35-39          20550
30-34          18753
25-29          16955
Name: AgeCategory, dtype: int64

In [24]:
def get_categorical(age):
    cat = ''
    if age == '18-24': cat = 18
    elif age == '25-29': cat = 25
    elif age == '30-34': cat = 30
    elif age == '35-39': cat = 35
    elif age == '40-44': cat = 40
    elif age == '45-49': cat = 45
    elif age == '50-54': cat = 50
    elif age == '55-59': cat = 55
    elif age == '60-64': cat = 60
    elif age == '65-69': cat = 65
    elif age == '70-74': cat = 70
    elif age == '75-79': cat = 75
    elif age == '80 or older': cat = 80
    
    return cat

df1['Age'] = df1['AgeCategory'].apply(lambda x : get_categorical(x))

df1.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,HeartDisease_No,HeartDisease_Yes,...,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy),Asthma_No,Asthma_Yes,KidneyDisease_No,KidneyDisease_Yes,SkinCancer_No,SkinCancer_Yes,Age
0,16.60,3.0,30.0,55-59,White,Yes,Very good,5.0,1,0,...,0,1,0,0,1,1,0,0,1,55
1,20.34,0.0,0.0,80 or older,White,Yes,Very good,7.0,1,0,...,0,0,0,1,0,1,0,1,0,80
2,26.58,20.0,30.0,65-69,White,Yes,Fair,8.0,1,0,...,0,1,0,0,1,1,0,1,0,65
3,24.21,0.0,0.0,75-79,White,No,Good,6.0,1,0,...,0,0,0,1,0,1,0,0,1,75
4,23.71,28.0,0.0,40-44,White,Yes,Very good,8.0,1,0,...,0,0,0,1,0,1,0,1,0,40

In [25]:
df1 = df1.drop('AgeCategory', axis = 1)
df1 = df1.drop('Race', axis = 1)
df1 = df1.drop('PhysicalActivity', axis = 1)

df1.head()

,BMI,PhysicalHealth,MentalHealth,GenHealth,SleepTime,HeartDisease_No,HeartDisease_Yes,Smoking_No,Smoking_Yes,AlcoholDrinking_No,...,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy),Asthma_No,Asthma_Yes,KidneyDisease_No,KidneyDisease_Yes,SkinCancer_No,SkinCancer_Yes,Age
0,16.60,3.0,30.0,Very good,5.0,1,0,0,1,1,...,0,1,0,0,1,1,0,0,1,55
1,20.34,0.0,0.0,Very good,7.0,1,0,1,0,1,...,0,0,0,1,0,1,0,1,0,80
2,26.58,20.0,30.0,Fair,8.0,1,0,0,1,1,...,0,1,0,0,1,1,0,1,0,65
3,24.21,0.0,0.0,Good,6.0,1,0,1,0,1,...,0,0,0,1,0,1,0,0,1,75
4,23.71,28.0,0.0,Very good,8.0,1,0,1,0,1,...,0,0,0,1,0,1,0,1,0,40

In [26]:
df1 = df1.drop('GenHealth', axis = 1)

In [27]:
df1 = df1.drop('Sex_Female', axis = 1)
df1 = df1.drop('Sex_Male', axis = 1)

In [28]:
#로지스틱 회귀를 사용해볼것이므로 StandardScaler를 사용하여 표준화를 진행하겠습니다.
from sklearn.preprocessing import StandardScaler

X_num = df1[['BMI', 'PhysicalHealth','MentalHealth', 'SleepTime','Age']]
X_cat = df1[['Smoking_No' , 'Smoking_Yes' , 'Diabetic_No, borderline diabetes', 'Diabetic_Yes', 'Diabetic_Yes (during pregnancy)',
             'Asthma_No', 'Asthma_Yes', 'KidneyDisease_No', 'KidneyDisease_Yes', 'SkinCancer_No', 'SkinCancer_Yes',
             'AlcoholDrinking_Yes', 'AlcoholDrinking_No', 'Stroke_Yes', 'Stroke_No', 'DiffWalking_Yes', 'DiffWalking_No']]
y = df1[['HeartDisease_Yes']]
scaler = StandardScaler() 
scaler.fit(X_num)
X_scaled = scaler.transform(X_num)
X_scaled = pd.DataFrame(data=X_scaled, index=X_num.index, columns=X_num.columns)
X = pd.concat([X_scaled, X_cat], axis=1)

In [29]:
X.head()

,BMI,PhysicalHealth,MentalHealth,SleepTime,Age,Smoking_No,Smoking_Yes,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy),...,KidneyDisease_No,KidneyDisease_Yes,SkinCancer_No,SkinCancer_Yes,AlcoholDrinking_Yes,AlcoholDrinking_No,Stroke_Yes,Stroke_No,DiffWalking_Yes,DiffWalking_No
0,-1.844750,-0.046751,3.281069,-1.460354,0.141621,0,1,0,1,0,...,1,0,0,1,0,1,0,1,0,1
1,-1.256338,-0.424070,-0.490039,-0.067601,1.525151,1,0,0,0,0,...,1,0,1,0,0,1,1,0,0,1
2,-0.274603,2.091388,3.281069,0.628776,0.695033,0,1,0,1,0,...,1,0,1,0,0,1,0,1,0,1
3,-0.647473,-0.424070,-0.490039,-0.763977,1.248445,1,0,0,0,0,...,1,0,0,1,0,1,0,1,0,1
4,-0.726138,3.097572,-0.490039,0.628776,-0.688497,1,0,0,0,0,...,1,0,1,0,0,1,0,1,1,0

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [31]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train, y_train)

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

LogisticRegression(max_iter=1000)

In [32]:
from sklearn.metrics import classification_report
pred = model_lr.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96     87796
           1       0.51      0.08      0.14      8143

    accuracy                           0.92     95939
   macro avg       0.71      0.54      0.55     95939
weighted avg       0.89      0.92      0.89     95939